### ISSUE TITLE
Error ejecutando primera vez

### ISSUE THREAD

**Issue by felipem775** [IHCantabria/THREDDSExplorer#1]
He descargado el zip del proyecto e instalado en windows en la siguiente ubicación:

```
C:\Users\mazaf\.qgis2\python\plugins\THREDDSExplorer
```

Cuando inicio QGis (2.12.0-Lyon), no me aparece el icono. Desde complementos intento activarlo y me encuentro con el siguiente error:

> No se pudo cargar el complemento 'processing' 
> 
> ImportError: cannot import name spatialite_utils 
> Traceback (most recent call last):
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 281, in loadPlugin
>     **import**(packageName)
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/Users/Felipe Maza/.qgis2/python/plugins\processing__init__.py", line 29, in 
>     from processing.tools.general import *
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/Users/Felipe Maza/.qgis2/python/plugins\processing\tools\general.py", line 28, in 
>     from processing.core.Processing import Processing
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 40, in 
>     from processing.core.GeoAlgorithm import GeoAlgorithm
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins\processing\core\GeoAlgorithm.py", line 41, in 
>     from processing.core.parameters import ParameterRaster, ParameterVector, ParameterMultipleInput, ParameterTable, Parameter
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins\processing\core\parameters.py", line 33, in 
>     from processing.tools.vector import resolveFieldIndex, features
>   File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/Users/Felipe Maza/.qgis2/python/plugins\processing\tools\vector.py", line 20, in 
>     from processing.algs.qgis import spatialite_utils
> ImportError: cannot import name spatialite_utils
> 
> Versión de Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
> Versión de QGIS: 2.12.0-Lyon Lyon, cd9d645 
> 
> Ruta de Python:
> C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins\processing
> C:/PROGRA~1/QGISLY~1/apps/qgis/./python
> C:/Users/Felipe Maza/.qgis2/python
> C:/Users/Felipe Maza/.qgis2/python/plugins
> C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
> C:\PROGRA~1\QGISLY~1\bin\python27.zip
> C:\PROGRA~1\QGISLY~1\apps\Python27\DLLs
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\plat-win
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\lib-tk
> C:\PROGRA~1\QGISLY~1\bin
> C:\PROGRA~1\QGISLY~1\apps\Python27
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\PIL
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\win32
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\win32\lib
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\Pythonwin
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
> C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
> C:/Users/Felipe Maza/.qgis2//python
> .
> C:\PROGRA~1\QGISLY~1\apps\qgis\python\plugins\fTools\tools

**Comment by beneditobordonau** [comment]
Necesitas tener instalado el plugin **processing**

Para instarlo ve al menú `complementos > Administar e instalar complementos` y selecciona el complemento: **processing**. 

Una vez instalado, reinicia QGIS.

**Comment by felipem775** [comment]
Ok, ya me aparece como instalado, no sé si se ha instalado al intentar activar THREDDSExplorer o ya estaba.

**Tras reiniciar QGis**, ya me carga el plugin THREDDSExplorer correctamente
